<?php
return array (
    ""=>array(
        "controller"=>"classes\ControllerHome",
        "action"=>"home"
    ),
    "basket"=>array(
        "controller"=>"classes\ControllerBasket",
        "action"=>"basket"
    ),
    "more"=>array(
        "controller"=>"classes\ControllerMore",
        "action"=>"more"
    ),
    "login"=>array(
        "controller"=>"classes\ControllerLogin",
        "action"=>"login"
    ),
    "logout"=>array(
        "controller"=>"classes\ControllerLogout",
        "action"=>"logout"
    ),
    "registration"=>array(
        "controller"=>"classes\ControllerRegistration",
        "action"=>"registration"
    )
);